services:
  app:
    image: node:current-slim
    ports:
      - 5173:5173
    volumes:
      - ./app:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    environment:
      TZ: Asia/Tokyo
      NODE_ENV: development
    command: tail -f /dev/null
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  node_modules:
