services:
  app:
    image: node:current-slim
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    environment:
      TZ: Asia/Tokyo
      NODE_ENV: development
    command: tail -f /dev/null
    stdin_open: true
    tty: true
    restart: unless-stopped
